# Generated by Django 4.2.16 on 2024-10-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_uploadedfile_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color_code',
            field=models.CharField(default='#33AFFF', max_length=20),
        ),
    ]
