# Generated by Django 4.2.16 on 2024-10-29 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='posts.post'),
            preserve_default=False,
        ),
    ]
