# Generated by Django 4.2.16 on 2024-11-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_sharedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedPost',
        ),
    ]
