# Generated by Django 4.2.16 on 2024-11-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_current_position'),
        ('posts', '0009_delete_sharedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
