# Generated by Django 4.2.16 on 2024-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='display_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
