# Generated by Django 4.2.16 on 2024-10-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_display_name_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
