# Generated by Django 4.2.16 on 2024-10-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='post',
            new_name='job',
        ),
    ]
