# Generated by Django 4.2.16 on 2024-10-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_post_uploadedfile_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
